[phases.setup]
# Inclut PHP, Composer, NodeJS (pour le frontend), et nginx si nécessaire
nixPkgs = ["php81", "composer", "nodejs", "nginx"]

[phases.install]
cmds = [
  "composer install --no-interaction --prefer-dist --optimize-autoloader",
  "cp .env.example .env",
  "php artisan key:generate"
]

[phases.build]
cmds = [
  "npm install",
  "npm run build"
]

[phases.start]
# Lancement du serveur Laravel
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
